### PR TITLE
Module 2: Leaderboard project wireframe

### PR DESCRIPTION
**Pull request by preciousakams**
### **Commit details**

- created Html page
- created style.css
- compiled project with webpack
- installed linters

### CODE REVIEW

**Review by Meltrust — COMMENTED** [review]
Hi @kamzzy,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a proper readme.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by AmaduKamara — CHANGES_REQUESTED** [review]
# Status: Required Changes ♻️♻️♻️ 

Hi @kamzzy, 

YoureDoingAGoodJobGreatJobGIF

Good job so far!
While you did well working on the project so far, there are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

# Required Changes

- [ ] For this project, you did not do any of the project requirements given. Kindly visit the project requirements which require you to hit the given API, and fetch and post leaderboard data to the API.

**See the project requirements given to you in the screenshot below**
image


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

```

**Review by OLIPLICHE — APPROVED** [review]
Hi @kamzzy , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by preciousakams** [comment]
Thank you

**Pull request merged**
